### ISSUE TITLE
Can rizon use the port of grpc-web?

### ISSUE THREAD

**Issue by Wangmmx** [rizon-world/mainnet#69]
Hello, I use the grpc-web method of cosmos to construct the transaction body, so I hope to use the same logic, but I didn't see the grpc-web url in the document, only rest API and  grpc url. And I built the node myself to open the port of grpc-web, but it didn't work either. So I want to ask if the related modules are not supported?

here‘s the node I built details 
https://github.com/rizon-world/rizon/issues/22

looking forward to your reply

**Comment by 0xmhha** [comment]
After Magnus(rizond version is v0.3.0) upgrade, you can use grpc-web.

**Comment by Wangmmx** [comment]
Thanks for you reply, and close the issue now
